name: dbt_run_scheduled_temp_test4
run-name: dbt_run_scheduled_temp_test4

on:
  workflow_dispatch:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/fsc-evm/.github/workflows/dbt_run_template_dev_refresh.yml@AN-5800/env-vars
    secrets: inherit