name: dbt_run_scheduled_temp_test1
run-name: dbt_run_scheduled_temp_test1

on:
  workflow_dispatch:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/fsc-evm/.github/workflows/dbt_run_template.yml@AN-5800/env-vars
    with:
      command_name: Run Main Models
      command: |
        dbt run -m "fsc_evm,tag:bronze_core"
      command_name_2: Run Streamline Models
      command_2: |
        dbt run -m "fsc_evm,tag:bronze_core"
    secrets: inherit