name: dbt_run_scheduled_temp_test5

on:
  push:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/fsc-evm/.github/workflows/dbt_run_template_docs_update.yml@AN-5800/env-vars
    secrets: inherit