name: dbt_run_integration_test
run-name: ${{ github.event.inputs.branch }}

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string

concurrency: ${{ github.workflow }}

jobs:
  prepare_vars:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}  
    outputs:  
      warehouse: ${{ steps.set_outputs.outputs.warehouse }}
    steps:
      - name: Set warehouse output
        id: set_outputs
        run: |
          echo "warehouse=${{ vars.WAREHOUSE }}" >> $GITHUB_OUTPUT  

  called_workflow_template:
    needs: prepare_vars
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/dbt.yml@main
    with:
      command: >
        dbt test --selector 'integration_tests'
      environment: ${{ inputs.environment }}
      warehouse: ${{ needs.prepare_vars.outputs.warehouse }}  
    secrets: inherit

  notify:
    runs-on: ubuntu-latest
    needs: run_dbt_jobs
    if: failure()
    environment: workflow_prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          pip install requests
          pip install -r requirements.txt
          dbt deps
          
      - name: Send Slack notification
        run: python macros/python/slack_alert.py
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}